export const data = [
  {
    id: 1,
    name: "Abdulhamidov Nurbek",
    age: 21,
    address: "Namangan",
    status: "Student",
    nickname: "Nurbek",
    univ: "Economical",
    job: "Frontend developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 2,
    name: "Muhtorov Azizbek",
    age: 21,
    address: "Uchqo'rg'on",
    status: "Mentor",
    nickname: "Axi",
    univ: "Westminister",
    job: "Frontend developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 3,
    name: "Nizamov Sardor",
    age: 21,
    address: "Namangan shahar",
    status: "Student",
    nickname: "Axi",
    univ: "Islam Academy",
    job: "Frontend developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 4,
    name: "Sultanov Hasanboy",
    age: 20,
    address: "Namangan shahar",
    status: "Seller",
    nickname: "Hasan",
    univ: "No",
    job: "Web developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 5,
    name: "Xoliqov Umarbek",
    age: 24,
    address: "Uchqo'r'gon",
    status: "Banker",
    nickname: "Basketball",
    univ: "No",
    job: "developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 6,
    name: "Abdulakhatov Islombek",
    age: 23,
    address: "Jizzax",
    status: "Mentor",
    nickname: "Islombek",
    univ: "TATU",
    job: "Web developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 7,
    name: "Yaxyoyev Shahboz",
    age: 18,
    address: "Samarqand",
    status: "Menejer",
    nickname: "Shahboz",
    univ: "TATU",
    job: "web developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 8,
    name: "Melibayev Ali",
    age: 28,
    address: "Tashkent",
    status: "Student",
    nickname: "Supporter",
    univ: "Thopmson",
    job: "Full stack developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 9,
    name: "Komiljonov Abdulloh",
    age: 30,
    address: "Tashkent",
    status: "Student",
    nickname: "k_abdulloh",
    univ: "Economica",
    job: "Full stack developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 10,
    name: "Boymamatov Dilshodbek",
    age: 27,
    address: "Jizzax",
    status: "Student",
    nickname: "webDev",
    univ: "TATU",
    job: "frontend developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 11,
    name: "Abdulhamidov Nurbek",
    age: 14,
    address: "Namangan",
    status: "Student",
    nickname: "Nurbek",
    univ: "Economica",
    job: "developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 12,
    name: "Abdulhamidov Nurbek",
    age: 13,
    address: "Namangan",
    status: "Student",
    nickname: "Nurbek",
    univ: "Economica",
    job: "developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 13,
    name: "Abdulhamidov Nurbek",
    age: 54,
    address: "Namangan",
    status: "Student",
    nickname: "Nurbek",
    univ: "Economica",
    job: "developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 14,
    name: "Abdulhamidov Nurbek",
    age: 23,
    address: "Namangan",
    status: "Student",
    nickname: "Nurbek",
    univ: "Economica",
    job: "developer",
    phone: "+998 94 044 70 64",
  },
  {
    id: 15,
    name: "Abdulhamidov Nurbek",
    age: 23,
    address: "Namangan",
    status: "Student",
    nickname: "Nurbek",
    univ: "Economica",
    job: "developer",
    phone: "+998 94 044 70 64",
  },
];
